#!/usr/bin/env python3
"""
Streaming Responses Example

This example demonstrates token-by-token streaming of LLM responses using LangChain's
streaming capabilities. Streaming provides a better user experience by showing incremental
results rather than waiting for the entire response.

Source: Agent Action Plan section 0.5.1 - Streaming patterns for responsive experiences
Source: libs/core/tests/unit_tests/runnables/test_runnable.py - Streaming implementation patterns

Key Concepts Demonstrated:
1. Basic streaming with .stream() method
2. Async streaming with .astream() method
3. Custom callback handler for streaming tokens
4. Streaming with RunnablePassthrough for complex chains
5. Performance comparison: streaming vs non-streaming
6. Comprehensive error handling for streaming operations

Requirements:
- langchain-core>=1.0.0
- python-dotenv
"""

import asyncio
import time
from typing import Any, Dict, List

from langchain_core.callbacks import BaseCallbackHandler
from langchain_core.language_models import FakeStreamingListLLM
from langchain_core.messages import AIMessage
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate, PromptTemplate
from langchain_core.runnables import RunnablePassthrough


# ==============================================================================
# Custom Streaming Callback Handler
# ==============================================================================

class StreamingCallbackHandler(BaseCallbackHandler):
    """
    Custom callback handler that processes streaming tokens in real-time.
    
    This handler demonstrates how to capture and process tokens as they arrive
    from the LLM, enabling custom streaming behaviors like real-time display,
    logging, or token-level analysis.
    
    Source: libs/core/langchain_core/callbacks/base.py
    Source: Agent Action Plan section 0.4.1 - Callback-based streaming patterns
    """
    
    def __init__(self) -> None:
        """Initialize the streaming callback handler with empty token storage."""
        super().__init__()
        self.tokens: List[str] = []
        self.token_count: int = 0
    
    def on_llm_new_token(self, token: str, **kwargs: Any) -> None:
        """
        Called when a new token is generated by the LLM.
        
        Args:
            token: The newly generated token string
            **kwargs: Additional metadata about the token generation
                - chunk: The message chunk if available
                - run_id: Unique identifier for this LLM run
        
        Note: This method is called synchronously during streaming, so avoid
        blocking operations here.
        """
        self.tokens.append(token)
        self.token_count += 1
        # Display token immediately with flush for real-time output
        print(token, end="", flush=True)
    
    def on_llm_end(self, response: Any, **kwargs: Any) -> None:
        """
        Called when LLM finishes generating the complete response.
        
        Args:
            response: The complete LLM response object
            **kwargs: Additional run metadata
        """
        print()  # New line after streaming completes
        print(f"\n[Streaming complete: {self.token_count} tokens received]")
    
    def reset(self) -> None:
        """Reset the handler state for reuse."""
        self.tokens = []
        self.token_count = 0


# ==============================================================================
# Example 1: Basic Streaming with .stream()
# ==============================================================================

def example_basic_streaming() -> None:
    """
    Demonstrate basic streaming using the .stream() method on a simple LCEL chain.
    
    Type Flow: Dict[str, str] → PromptTemplate → str → FakeStreamingListLLM → str chunks
    
    The .stream() method returns an iterator that yields response chunks as they
    are generated, allowing token-by-token display.
    
    Source: libs/core/tests/unit_tests/runnables/test_runnable.py:1050
    """
    print("=" * 80)
    print("Example 1: Basic Streaming with .stream()")
    print("=" * 80)
    
    try:
        # Create a simple prompt template
        prompt = PromptTemplate.from_template(
            "You are a helpful assistant. Answer the following question: {question}"
        )
        
        # Create a fake streaming LLM for demonstration
        # This simulates token-by-token generation without requiring API keys
        llm = FakeStreamingListLLM(
            responses=[
                "Streaming allows you to receive and display tokens as they are generated, "
                "providing a more responsive user experience instead of waiting for the "
                "complete response."
            ]
        )
        
        # Create LCEL chain: prompt | llm
        # Type flow: Dict → PromptValue → Iterator[str]
        chain = prompt | llm
        
        # Invoke with streaming
        print("\nQuestion: What is streaming in LangChain?")
        print("Streaming response: ", end="", flush=True)
        
        # Collect chunks for analysis
        chunks = []
        for chunk in chain.stream({"question": "What is streaming in LangChain?"}):
            # Each chunk is a token string
            print(chunk, end="", flush=True)
            chunks.append(chunk)
        
        print(f"\n\n✓ Received {len(chunks)} chunks")
        print(f"  First chunk: '{chunks[0] if chunks else 'N/A'}'")
        print(f"  Last chunk: '{chunks[-1] if chunks else 'N/A'}'")
        
    except Exception as e:
        print(f"\n✗ Error in basic streaming: {e}")
        print(f"  Error type: {type(e).__name__}")


# ==============================================================================
# Example 2: Streaming with Custom Callback Handler
# ==============================================================================

def example_streaming_with_callback() -> None:
    """
    Demonstrate streaming using a custom callback handler.
    
    Callbacks provide an alternative streaming mechanism where tokens are
    intercepted via the on_llm_new_token callback method. This is useful for:
    - Custom token processing logic
    - Logging or monitoring token generation
    - Implementing custom display logic
    
    Source: libs/core/langchain_core/callbacks/base.py
    Source: Agent Action Plan section 0.4.1 - Custom callback patterns
    """
    print("\n" + "=" * 80)
    print("Example 2: Streaming with Custom Callback Handler")
    print("=" * 80)
    
    try:
        prompt = PromptTemplate.from_template(
            "Explain in simple terms: {topic}"
        )
        
        llm = FakeStreamingListLLM(
            responses=[
                "A callback handler is a class that intercepts events during chain execution, "
                "allowing you to add custom behavior like logging, monitoring, or real-time "
                "token processing during streaming."
            ]
        )
        
        # Create custom callback handler
        callback = StreamingCallbackHandler()
        
        # Create chain
        chain = prompt | llm
        
        print("\nTopic: What is a callback handler?")
        print("Streaming with callback: ", end="", flush=True)
        
        # Invoke with callback in config
        # The callback's on_llm_new_token will be called for each token
        response = chain.invoke(
            {"topic": "What is a callback handler?"},
            {"callbacks": [callback]}
        )
        
        print(f"\n✓ Complete response length: {len(response)} characters")
        print(f"  Tokens captured by callback: {callback.token_count}")
        
    except Exception as e:
        print(f"\n✗ Error in callback streaming: {e}")
        print(f"  Error type: {type(e).__name__}")


# ==============================================================================
# Example 3: Streaming with Output Parser
# ==============================================================================

def example_streaming_with_parser() -> None:
    """
    Demonstrate streaming through a complete LCEL chain with output parsing.
    
    Type Flow: 
    Dict[str, str] → ChatPromptTemplate → List[BaseMessage] → 
    FakeStreamingListLLM → AIMessage chunks → StrOutputParser → str chunks
    
    The StrOutputParser converts AIMessage chunks to string chunks while
    maintaining streaming behavior.
    
    Source: libs/core/tests/unit_tests/runnables/test_runnable.py:1851
    """
    print("\n" + "=" * 80)
    print("Example 3: Streaming with Output Parser")
    print("=" * 80)
    
    try:
        # Create chat prompt template
        prompt = ChatPromptTemplate.from_messages([
            ("system", "You are a helpful coding assistant."),
            ("human", "{question}")
        ])
        
        # Create streaming LLM
        llm = FakeStreamingListLLM(
            responses=[
                "Here is a simple Python function:\n\ndef greet(name):\n    "
                "return f'Hello, {name}!'\n\nThis function takes a name and "
                "returns a greeting."
            ]
        )
        
        # Create string output parser
        parser = StrOutputParser()
        
        # Build LCEL chain: prompt | llm | parser
        chain = prompt | llm | parser
        
        print("\nQuestion: Write a simple Python function")
        print("Streaming response:\n")
        
        # Stream with parser
        full_response = ""
        for chunk in chain.stream({"question": "Write a simple Python function"}):
            # Parser converts message chunks to string chunks
            print(chunk, end="", flush=True)
            full_response += chunk
        
        print(f"\n\n✓ Streaming complete")
        print(f"  Total response length: {len(full_response)} characters")
        
    except Exception as e:
        print(f"\n✗ Error in parser streaming: {e}")
        print(f"  Error type: {type(e).__name__}")


# ==============================================================================
# Example 4: Async Streaming with .astream()
# ==============================================================================

async def example_async_streaming() -> None:
    """
    Demonstrate asynchronous streaming using .astream() method.
    
    Async streaming is essential for:
    - Non-blocking operations in async applications
    - Concurrent request handling in web servers
    - Integration with async frameworks (FastAPI, aiohttp, etc.)
    
    Type Flow: Dict → PromptTemplate → AsyncIterator[str]
    
    Source: libs/core/tests/unit_tests/runnables/test_runnable.py:1958
    """
    print("\n" + "=" * 80)
    print("Example 4: Async Streaming with .astream()")
    print("=" * 80)
    
    try:
        prompt = PromptTemplate.from_template(
            "Describe the benefits of: {concept}"
        )
        
        llm = FakeStreamingListLLM(
            responses=[
                "Async streaming provides non-blocking I/O operations, allowing your "
                "application to handle multiple concurrent requests efficiently. "
                "It's particularly valuable in web servers where you need to serve "
                "many users simultaneously without thread-per-request overhead."
            ]
        )
        
        chain = prompt | llm
        
        print("\nConcept: Async streaming")
        print("Async streaming response: ", end="", flush=True)
        
        # Async iteration over stream
        chunks_received = 0
        async for chunk in chain.astream({"concept": "async streaming"}):
            print(chunk, end="", flush=True)
            chunks_received += 1
            # Simulate async processing (e.g., writing to async database)
            await asyncio.sleep(0.01)
        
        print(f"\n\n✓ Async streaming complete")
        print(f"  Chunks received: {chunks_received}")
        
    except Exception as e:
        print(f"\n✗ Error in async streaming: {e}")
        print(f"  Error type: {type(e).__name__}")


# ==============================================================================
# Example 5: Streaming with RunnablePassthrough (Complex Chain)
# ==============================================================================

def example_streaming_with_passthrough() -> None:
    """
    Demonstrate streaming through complex chains using RunnablePassthrough.
    
    RunnablePassthrough allows you to pass data through a chain while applying
    transformations, which is useful for:
    - Maintaining context while processing
    - Building complex multi-step chains
    - Implementing RAG (Retrieval-Augmented Generation) patterns
    
    Type Flow: Dict → RunnablePassthrough → PromptTemplate → str chunks
    
    Source: libs/core/tests/unit_tests/runnables/test_runnable.py:1050
    Source: Agent Action Plan section 0.3.1 - Complex chain streaming
    """
    print("\n" + "=" * 80)
    print("Example 5: Streaming with RunnablePassthrough")
    print("=" * 80)
    
    try:
        # Create a chain that passes through the question and adds context
        prompt = PromptTemplate.from_template(
            "Context: {context}\n\nQuestion: {question}\n\nAnswer:"
        )
        
        llm = FakeStreamingListLLM(
            responses=[
                "Based on the provided context, LangChain is designed with streaming "
                "as a first-class feature. Every runnable supports streaming through "
                "the .stream() and .astream() methods, making it easy to build "
                "responsive applications."
            ]
        )
        
        # Build complex chain with passthrough
        # RunnablePassthrough.assign adds new keys while preserving existing ones
        chain = (
            RunnablePassthrough.assign(
                context=lambda x: "LangChain is a framework for building LLM applications."
            )
            | prompt
            | llm
        )
        
        print("\nQuestion: How does LangChain handle streaming?")
        print("Streaming response: ", end="", flush=True)
        
        for chunk in chain.stream({"question": "How does LangChain handle streaming?"}):
            print(chunk, end="", flush=True)
        
        print("\n\n✓ Complex chain streaming complete")
        
    except Exception as e:
        print(f"\n✗ Error in passthrough streaming: {e}")
        print(f"  Error type: {type(e).__name__}")


# ==============================================================================
# Example 6: Performance Comparison - Streaming vs Non-Streaming
# ==============================================================================

def example_performance_comparison() -> None:
    """
    Compare performance characteristics of streaming vs non-streaming invocation.
    
    Key metrics:
    - Time to first token (TTFT): How quickly user sees initial response
    - Total time: Overall response generation time
    - User experience: Perceived responsiveness
    
    Streaming advantage: Lower perceived latency due to incremental display
    Non-streaming advantage: Simpler implementation for batch processing
    
    Source: Agent Action Plan section 0.4.1 - Performance demonstration
    """
    print("\n" + "=" * 80)
    print("Example 6: Performance Comparison")
    print("=" * 80)
    
    try:
        prompt = PromptTemplate.from_template("Explain: {topic}")
        llm = FakeStreamingListLLM(
            responses=[
                "Performance comparison reveals that streaming provides better user "
                "experience through incremental display, even if total generation "
                "time is similar. Users perceive streaming responses as faster "
                "because they see progress immediately."
            ]
        )
        chain = prompt | llm
        
        # Non-streaming invocation
        print("\n1. Non-streaming invocation:")
        print("   Waiting for complete response...", end="", flush=True)
        start_time = time.time()
        response = chain.invoke({"topic": "streaming performance"})
        end_time = time.time()
        print(f" Done!")
        print(f"   Time to complete: {(end_time - start_time) * 1000:.2f}ms")
        print(f"   Response length: {len(response)} characters")
        print(f"   User sees nothing until: {(end_time - start_time) * 1000:.2f}ms")
        
        # Streaming invocation
        print("\n2. Streaming invocation:")
        print("   Streaming response: ", end="", flush=True)
        start_time = time.time()
        first_token_time = None
        chunks = []
        
        for i, chunk in enumerate(chain.stream({"topic": "streaming performance"})):
            if i == 0:
                first_token_time = time.time()
            chunks.append(chunk)
        
        end_time = time.time()
        print()
        
        ttft = (first_token_time - start_time) * 1000 if first_token_time else 0
        total_time = (end_time - start_time) * 1000
        
        print(f"   Time to first token (TTFT): {ttft:.2f}ms")
        print(f"   Total time: {total_time:.2f}ms")
        print(f"   Chunks received: {len(chunks)}")
        print(f"   User sees content starting at: {ttft:.2f}ms ← Much better UX!")
        
        print("\n✓ Performance comparison complete")
        print("  Key insight: Streaming reduces perceived latency")
        
    except Exception as e:
        print(f"\n✗ Error in performance comparison: {e}")
        print(f"  Error type: {type(e).__name__}")


# ==============================================================================
# Example 7: Streaming Error Handling
# ==============================================================================

def example_streaming_error_handling() -> None:
    """
    Demonstrate comprehensive error handling for streaming operations.
    
    Common streaming errors:
    - Network interruptions during streaming
    - Timeout errors on long-running streams
    - Invalid token parsing errors
    - Rate limiting during streaming
    
    Best practices:
    - Always wrap streaming operations in try-except
    - Handle partial responses gracefully
    - Provide user feedback on streaming failures
    - Implement retry logic for transient errors
    
    Source: Agent Action Plan section 0.1.1 - Comprehensive error handling
    """
    print("\n" + "=" * 80)
    print("Example 7: Streaming Error Handling")
    print("=" * 80)
    
    try:
        prompt = PromptTemplate.from_template("Answer: {query}")
        llm = FakeStreamingListLLM(responses=["This is a successful streaming response."])
        chain = prompt | llm
        
        print("\n1. Handling successful streaming:")
        accumulated_response = ""
        try:
            for chunk in chain.stream({"query": "test"}):
                accumulated_response += chunk
            print(f"   ✓ Successfully streamed {len(accumulated_response)} characters")
        except Exception as stream_error:
            print(f"   ✗ Streaming failed: {stream_error}")
            print(f"   Partial response received: {accumulated_response}")
        
        print("\n2. Handling streaming with timeout protection:")
        accumulated_response = ""
        timeout_seconds = 30
        start = time.time()
        try:
            for chunk in chain.stream({"query": "test with timeout"}):
                if time.time() - start > timeout_seconds:
                    raise TimeoutError(f"Streaming exceeded {timeout_seconds}s timeout")
                accumulated_response += chunk
            print(f"   ✓ Streaming completed within timeout")
        except TimeoutError as te:
            print(f"   ✗ {te}")
            print(f"   Partial response: {accumulated_response[:50]}...")
        except Exception as e:
            print(f"   ✗ Unexpected error: {e}")
        
        print("\n3. Handling empty streams:")
        try:
            empty_llm = FakeStreamingListLLM(responses=[""])
            empty_chain = prompt | empty_llm
            chunks = list(empty_chain.stream({"query": "empty test"}))
            if not chunks or all(not c for c in chunks):
                print("   ⚠ Warning: Received empty stream")
            else:
                print(f"   ✓ Received {len(chunks)} chunks")
        except Exception as e:
            print(f"   ✗ Error handling empty stream: {e}")
        
        print("\n✓ Error handling demonstration complete")
        print("  Best practice: Always handle streaming errors gracefully")
        
    except Exception as e:
        print(f"\n✗ Error in error handling example: {e}")
        print(f"  Error type: {type(e).__name__}")


# ==============================================================================
# Main Execution
# ==============================================================================

def main() -> None:
    """
    Execute all streaming examples in sequence.
    
    This main function demonstrates the complete range of LangChain streaming
    capabilities, from basic streaming to advanced async patterns and error
    handling.
    
    Examples are designed to be:
    - Self-contained and executable without external dependencies (using Fake models)
    - Comprehensive in coverage of streaming patterns
    - Production-ready with proper error handling
    - Well-documented with inline explanations
    
    Source: Agent Action Plan section 0.9.2 - Example format standards
    """
    print("\n")
    print("╔" + "═" * 78 + "╗")
    print("║" + " " * 20 + "LangChain Streaming Responses Example" + " " * 21 + "║")
    print("╚" + "═" * 78 + "╝")
    print("\nThis example demonstrates comprehensive streaming patterns in LangChain.")
    print("All examples use FakeStreamingListLLM for demonstration without API keys.")
    print()
    
    # Execute synchronous examples
    example_basic_streaming()
    example_streaming_with_callback()
    example_streaming_with_parser()
    example_streaming_with_passthrough()
    example_performance_comparison()
    example_streaming_error_handling()
    
    # Execute async example
    print("\n" + "=" * 80)
    print("Running async example...")
    print("=" * 80)
    asyncio.run(example_async_streaming())
    
    # Summary
    print("\n" + "=" * 80)
    print("Summary: Streaming Best Practices")
    print("=" * 80)
    print("""
Key Takeaways:
1. Use .stream() for synchronous streaming, .astream() for async
2. Streaming reduces perceived latency by showing incremental results
3. Custom callbacks enable token-level processing and monitoring
4. Output parsers maintain streaming behavior through transformation chains
5. RunnablePassthrough allows complex chains while preserving streaming
6. Always implement comprehensive error handling for production streams
7. Consider timeout protection for long-running streaming operations

When to use streaming:
✓ Interactive chat applications
✓ Real-time content generation
✓ Long-form text generation where immediate feedback is valuable
✓ Applications where perceived responsiveness matters

When non-streaming may be better:
✓ Batch processing scenarios
✓ When you need the complete response for validation
✓ Simple scripts where complexity isn't justified
✓ Cases where response assembly logic requires the full text

For production use with real LLMs:
- Replace FakeStreamingListLLM with actual model (e.g., ChatOpenAI)
- Set streaming=True in model configuration
- Implement robust error handling and retry logic
- Add monitoring for streaming performance metrics
- Consider implementing streaming timeouts
    """)
    
    print("\n" + "=" * 80)
    print("All examples completed successfully!")
    print("=" * 80)


if __name__ == "__main__":
    main()
